pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'pip install -r requirements.txt --break-system-packages'
                sh ' pip install --upgrade flask --break-system-packages'
            }
        }
        stage('Unit Test') {
            steps {
                sh 'python3 test_point_manager.py'
            }
            post {
                always {
                    junit 'test-reports/*.xml'
                }
            }
        }
        stage('Integration Test') {
            steps {
                sh 'python3 test_points_api.py'
            }
            post {
                always {
                    junit 'api-test-reports/*.xml'
                }
            }
        }
    }
}
