pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'pip install -r requirements.txt --break-system-packages'
                sh ' pip install --upgrade flask --break-system-packages'
            }
        }
        stage('Unit Test') {
            steps {
                sh 'python3 -m unittest test_point_manager'
            }
        }
    }
}
